
"use client";

import React, { useState } from 'react';
import { useFinance, Transaction } from '@/context/FinanceContext';
import { formatINR } from '@/lib/utils';
import { 
  Search, Filter, Download, Trash2, 
  ArrowUpCircle, ArrowDownCircle, Plus, FileText
} from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { 
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue 
} from '@/components/ui/select';
import { motion, AnimatePresence } from 'framer-motion';
import { AddTransactionModal } from './AddTransactionModal';

export const TransactionList = () => {
  const { transactions, userRole, deleteTransaction, user } = useFinance();
  const [searchTerm, setSearchTerm] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);

  const categories = Array.from(new Set(transactions.map(t => t.category)));

  const filteredTransactions = transactions.filter(t => {
    const matchesSearch = t.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = categoryFilter === 'all' || t.category === categoryFilter;
    return matchesSearch && matchesCategory;
  });

  const exportCSV = () => {
    const timestamp = new Date().toLocaleString();
    const metaHeader = [
      ['ZORVYN FINANCIAL SYSTEMS - OFFICIAL LEDGER EXPORT'],
      [`Generated by: ${user?.name || 'Anonymous Node'} (${user?.email || 'N/A'})`],
      [`Timestamp: ${timestamp}`],
      [`Security Protocol: AES-256-GCM Verified`],
      [''], // Empty row
    ];

    const headers = ['Date', 'Description', 'Amount', 'Category', 'Type'];
    const rows = filteredTransactions.map(t => [
      t.date, t.description, t.amount, t.category, t.type
    ]);

    const csvContent = "data:text/csv;charset=utf-8," 
      + metaHeader.map(e => e.join(",")).join("\n")
      + "\n"
      + headers.join(",") + "\n" 
      + rows.map(e => e.join(",")).join("\n");
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Zorvyn_Ledger_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass-card mt-6 rounded-[2rem] border border-slate-800/50 overflow-hidden"
    >
      <div className="p-8 border-b border-slate-800/50 flex flex-col xl:flex-row xl:items-center justify-between gap-6">
        <div>
          <h3 className="text-xl font-black text-white italic uppercase tracking-tight flex items-center gap-3">
            <div className="p-2 bg-primary/10 rounded-xl border border-primary/20">
              <FileText className="w-5 h-5 text-primary" />
            </div>
            Ledger Terminal
          </h3>
          <p className="text-[9px] text-slate-500 font-black uppercase tracking-[3px] mt-2 opacity-70">
            {filteredTransactions.length} Transactions Found
          </p>
        </div>
        
        <div className="flex flex-wrap items-center gap-4">
          <div className="relative min-w-[280px]">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-600" />
            <Input 
              placeholder="Search transactions..." 
              className="pl-12 bg-slate-900/50 border-slate-800 focus:ring-primary h-12 text-[10px] font-black uppercase tracking-[1px] rounded-xl"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          
          <Select value={categoryFilter} onValueChange={setCategoryFilter}>
            <SelectTrigger className="w-[180px] bg-slate-900/50 border-slate-800 h-12 rounded-xl text-[10px] font-black uppercase tracking-[1px]">
              <SelectValue placeholder="Category" />
            </SelectTrigger>
            <SelectContent className="bg-slate-950 border-slate-800 text-white">
              <SelectItem value="all" className="text-[10px] font-black uppercase">All Categories</SelectItem>
              {categories.map(cat => (
                <SelectItem key={cat} value={cat} className="text-[10px] font-black uppercase">{cat}</SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Button 
            variant="outline" 
            size="sm" 
            onClick={exportCSV}
            className="h-12 border-slate-800 hover:bg-slate-800/50 text-[10px] font-black uppercase tracking-[2px] px-6 rounded-xl"
          >
            <Download className="w-4 h-4 mr-2" />
            Export CSV
          </Button>

          {userRole === 'Admin' && (
            <Button size="sm" onClick={() => setIsAddModalOpen(true)} className="h-12 bg-primary text-primary-foreground text-[10px] font-black uppercase tracking-[2px] px-8 rounded-xl shadow-[0_0_20px_rgba(59,130,246,0.3)]">
              <Plus className="w-4 h-4 mr-2" />
              Add Transaction
            </Button>
          )}
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse min-w-[1000px]">
          <thead>
            <tr className="bg-slate-900/50 text-slate-500 text-[10px] uppercase tracking-[3px] font-black italic">
              <th className="px-8 py-6">Date</th>
              <th className="px-8 py-6">Description</th>
              <th className="px-8 py-6">Category</th>
              <th className="px-8 py-6">Amount</th>
              <th className="px-8 py-6 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/30">
            <AnimatePresence mode='popLayout'>
              {filteredTransactions.length > 0 ? (
                filteredTransactions.map((t) => (
                  <motion.tr 
                    key={t.id}
                    layout
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0, x: -20 }}
                    className="hover:bg-slate-900/20 transition-all group"
                  >
                    <td className="px-8 py-6 text-[11px] font-bold text-slate-400 font-mono">
                      {new Date(t.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase()}
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex items-center gap-4">
                        <div className={`p-2 rounded-lg ${t.type === 'Income' ? 'bg-emerald-500/10 text-emerald-500' : 'bg-rose-500/10 text-rose-500'}`}>
                          {t.type === 'Income' ? (
                            <ArrowUpCircle className="w-4 h-4" />
                          ) : (
                            <ArrowDownCircle className="w-4 h-4" />
                          )}
                        </div>
                        <span className="text-sm font-black text-white italic tracking-tight">{t.description}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <span className="inline-flex items-center px-4 py-1.5 rounded-full text-[9px] font-black bg-slate-900/80 text-primary border border-primary/20 uppercase tracking-[2px]">
                        {t.category}
                      </span>
                    </td>
                    <td className={`px-8 py-6 text-sm font-black italic ${t.type === 'Income' ? 'text-emerald-400' : 'text-rose-400'}`}>
                      {t.type === 'Income' ? '+' : '-'}{formatINR(t.amount)}
                    </td>
                    <td className="px-8 py-6 text-center">
                      {userRole === 'Admin' ? (
                        <Button 
                          variant="ghost" 
                          size="icon" 
                          onClick={() => deleteTransaction(t.id)}
                          className="hover:bg-rose-500/10 hover:text-rose-400 text-slate-700 transition-all rounded-xl"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      ) : (
                        <span className="text-[9px] text-slate-700 font-black uppercase tracking-[2px] italic">Read Only</span>
                      )}
                    </td>
                  </motion.tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="px-8 py-24 text-center">
                    <div className="flex flex-col items-center gap-4">
                      <Search className="w-12 h-12 text-slate-800 animate-pulse" />
                      <p className="text-[10px] text-slate-600 font-black uppercase tracking-[4px] italic">No transactions found.</p>
                    </div>
                  </td>
                </tr>
              )}
            </AnimatePresence>
          </tbody>
        </table>
      </div>

      <AddTransactionModal 
        isOpen={isAddModalOpen} 
        onClose={() => setIsAddModalOpen(false)} 
      />
    </motion.div>
  );
};
