
"use client";

import React, { useState } from 'react';
import { useFinance } from '@/context/FinanceContext';
import { formatINR } from '@/lib/utils';
import { Search, Plus, Trash2, Download, ShieldCheck, Lock } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { AddTransactionModal } from './AddTransactionModal';
import { motion, AnimatePresence } from 'framer-motion';

export const TransactionList = () => {
  const { transactions, userRole, deleteTransaction } = useFinance();
  const [searchTerm, setSearchTerm] = useState('');
  const [isModalOpen, setIsModalOpen] = useState(false);

  const filtered = transactions.filter(t => 
    t.category.toLowerCase().includes(searchTerm.toLowerCase()) ||
    t.description.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const exportCSV = () => {
    if (userRole !== 'Admin') return;
    const headers = [
      "ZORVYN FINANCIAL REPORT\n",
      "SECURITY PROTOCOL: AES-256-CLIENT-AUDIT\n",
      `GENERATED BY: SYSTEM_NODE_AUTO\n`,
      `TIMESTAMP: ${new Date().toLocaleString()}\n\n`,
      "Date,Description,Category,Amount,Type\n"
    ];
    const rows = filtered.map(t => `${t.date},${t.description},${t.category},${t.amount},${t.type}`).join("\n");
    const blob = new Blob([...headers, rows], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Zorvyn_Audit_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
  };

  return (
    <Card className="border-none shadow-sm bg-white dark:bg-slate-950">
      <CardHeader className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-7">
        <div className="space-y-1">
          <CardTitle className="text-lg font-bold text-slate-900 dark:text-white">Recent Ledger Activity</CardTitle>
          <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">
            {userRole === 'Admin' ? 'Mode: Full Audit Access' : 'Mode: Standard User Ledger'}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto">
          <div className="relative flex-1 sm:flex-none">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <Input 
              placeholder="Search nodes..." 
              className="pl-9 w-full sm:w-[250px] bg-slate-50 dark:bg-slate-900 border-slate-100 dark:border-slate-800"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          
          {userRole === 'Admin' && (
            <Button variant="outline" size="sm" onClick={exportCSV} className="text-slate-600 dark:text-slate-400 border-slate-200 dark:border-slate-800">
              <Download className="w-4 h-4 mr-2" />
              CSV Report
            </Button>
          )}

          <Button 
            size="sm" 
            onClick={() => setIsModalOpen(true)} 
            className="bg-indigo-600 hover:bg-indigo-700 text-white shadow-indigo-200 dark:shadow-none shadow-lg"
          >
            <Plus className="w-4 h-4 mr-2" />
            Add Transaction
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="text-slate-400 text-[10px] font-black uppercase tracking-widest border-b border-slate-50 dark:border-slate-900">
                <th className="pb-4 font-black">Temporal Node</th>
                <th className="pb-4 font-black">Entity Description</th>
                <th className="pb-4 font-black">Classification</th>
                <th className="pb-4 font-black">Quantum Amount</th>
                <th className="pb-4 font-black text-right">Audit Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50 dark:divide-slate-900">
              <AnimatePresence>
                {filtered.map((t) => (
                  <motion.tr 
                    key={t.id} 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="text-sm group hover:bg-slate-50/50 dark:hover:bg-slate-900/50 transition-colors"
                  >
                    <td className="py-4 text-slate-500 font-medium">{t.date}</td>
                    <td className="py-4 font-bold text-slate-900 dark:text-slate-200">{t.description}</td>
                    <td className="py-4">
                      <span className="bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-tight">
                        {t.category}
                      </span>
                    </td>
                    <td className={`py-4 font-black ${t.type === 'Income' ? 'text-emerald-600' : 'text-rose-500'}`}>
                      {t.type === 'Income' ? '+' : '-'}{formatINR(t.amount)}
                    </td>
                    <td className="py-4 text-right">
                      {userRole === 'Admin' ? (
                        <Button 
                          variant="ghost" 
                          size="sm" 
                          onClick={() => deleteTransaction(t.id)}
                          className="text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-950/30"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      ) : (
                        <div className="flex justify-end pr-2 opacity-30">
                          <Lock className="w-4 h-4 text-slate-400" />
                        </div>
                      )}
                    </td>
                  </motion.tr>
                ))}
              </AnimatePresence>
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={5} className="py-16 text-center">
                    <div className="flex flex-col items-center gap-3">
                      <div className="w-12 h-12 bg-slate-50 dark:bg-slate-900 rounded-full flex items-center justify-center">
                        <Search className="w-6 h-6 text-slate-200 dark:text-slate-800" />
                      </div>
                      <div>
                        <p className="text-sm font-bold text-slate-900 dark:text-white">No transactions found</p>
                        <p className="text-xs text-slate-500">Audit criteria returned zero nodes.</p>
                      </div>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </CardContent>
      <AddTransactionModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />
    </Card>
  );
};
